# ============================================================
# acl.conf — Regole di accesso MQTT per Locale 2 (SALA_GIOCHI_ROMA)
# Connected Games Platform (PISSIR A.A. 2025/2026)
# ============================================================

# Utente simulatore: può solo pubblicare eventi
user simulator
topic write locale/SALA_GIOCHI_ROMA/eventi

# Utente Edge: può solo sottoscrivere agli eventi
user edge-client
topic read locale/SALA_GIOCHI_ROMA/eventi
