# Regole di accesso MQTT per Locale 2 (SALA_GIOCHI_ROMA): simulator scrive, edge-client legge.

user simulator
topic write locale/SALA_GIOCHI_ROMA/eventi

user edge-client
topic read locale/SALA_GIOCHI_ROMA/eventi
