# ============================================================
# mosquitto.conf — Broker MQTT per Locale 2 (SALA_GIOCHI_ROMA)
# Connected Games Platform (PISSIR A.A. 2025/2026)
# ============================================================

listener 1883

allow_anonymous false

password_file /mosquitto/data/password_file

acl_file /mosquitto/config/acl-locale2.conf

log_dest stdout
log_type all
connection_messages true
