# Configurazione broker MQTTS per Locale 1

listener 8883
certfile /mosquitto/data/server.crt
keyfile /mosquitto/data/server.key

allow_anonymous false
password_file /mosquitto/data/password_file
acl_file /mosquitto/config/acl-locale1.conf

log_dest stdout
log_type information
log_type error
connection_messages false
