#!/bin/bash
set -e

# Creazione dinamica database ed utenti tramite variabili d'ambiente (.env)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE platform_db;
    CREATE DATABASE keycloak_db;

    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$PLATFORM_DB_USER') THEN
            CREATE USER $PLATFORM_DB_USER WITH PASSWORD '$PLATFORM_DB_PASSWORD';
        END IF;
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$KEYCLOAK_DB_USER') THEN
            CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
        END IF;
    END
    \$\$;

    GRANT ALL PRIVILEGES ON DATABASE platform_db TO $PLATFORM_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE keycloak_db TO $KEYCLOAK_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "platform_db" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS platform_db;
    GRANT ALL PRIVILEGES ON SCHEMA platform_db TO $PLATFORM_DB_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA platform_db TO $PLATFORM_DB_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA platform_db TO $PLATFORM_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA platform_db GRANT ALL ON TABLES TO $PLATFORM_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA platform_db GRANT ALL ON SEQUENCES TO $PLATFORM_DB_USER;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA platform_db;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "keycloak_db" <<-EOSQL
    GRANT ALL PRIVILEGES ON SCHEMA public TO $KEYCLOAK_DB_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $KEYCLOAK_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $KEYCLOAK_DB_USER;
EOSQL
